### PR TITLE
Subscribing to machines

### LINKED ISSUE #60: Allow users to change their subscribed machines
As a technician/admin I want to change my subscribed machines that I can access so that I can get the relevant info for predictive maintenance.

**Acceptance Criteria**

 - User is able to add subscribed machines
 - User is able to remove subscribed machines
 - Only subscribed machines show up on the user's machines page.

**Is your feature request related to a problem? Please describe.**
- Each user will use the app to track different machines, currently it displays all machines to every user

**Describe the solution you'd like**
- Each user has machines they are subscribed to, linked by an array in the database
- On the machines page, the user can choose whether to see all machines or just the ones they’re subscribed to
- On each machine’s page (Sensor page), the user can subscribe/unsubscribe from that machine with a button which mutates the database.
- When user adds a new machine, automatically subscribe the user to that machine.

**Describe alternatives you've considered**
- User could subscribe to a specific individual machine by inputting that machine's ID into a modal on the machines page.

**Additional context**

### PR DESCRIPTION
**Pull request by merw957**
## GitHub Issue Solved:

closes #60 

## Current behaviour

- All machines are displayed on the machines page
- Users cannot choose specific machines they want to see/subscribe to

## Changed behaviour

- Each user has machines they are subscribed to, linked by an array in the database
- On the machines page, the user can choose whether to see all machines or just the ones they’re subscribed to
- On each machine’s page (Sensor page), the user can subscribe/unsubscribe from that machine with a button which mutates the database.
- When user adds a new machine, the user is automatically subscribed to that machine.
- If user doesn't exist when subscribing to a machine, a new user is created.
- Removed the random images for machines without images in the db

## PR checklist

Remember to check the following

 - [x] Tag specific people to review your PR
 - [ ] Update the ReadMe with any new run instructions
 - [x] Closes the associated issue (if applicable)
 - [x] Updated kanban board

## Notes

- Added a set of queries and mutations for the Users collection.

### Demo

image

image

- Run the code, go to the machines page
- By default, it shows you your subscribed machines (it will probably say you are not subscribed to any machines, because you haven't subscribed to any yet).
- Click "all machines" to show all machines.
- Click "subscribed machines" to show only your subscribed machines again.
- Click on a machine to go to its sensors page.
- Click "subscribe to machine" to subscribe to the machine.
- Go back to the machines page, the subscribed machine should now be there.
- Click on the machine again, and click "unsubscribe from machine".
- Go back to the machines page, and it should be empty again.

### Run instructions

- Same as before

### CODE REVIEW

**Review by margeobur — DISMISSED** [review]
This was very satisfying to review because everything just worked :) 

I checked it out and tried out all the steps of subscribing, unsubscribing, etc.  and passed my eyes over the code - it all checks out. Great job 💯

**Review by margeobur — APPROVED** [review]

**Review by FrankWangma — CHANGES_REQUESTED** [review]
Everything's looking mostly good, but there are some bugs.
- Firstly, you should put a default value for the radio(?) button so that it looks like its selected
image
- Secondly, I've found a bug that happens with creating a new user.
At least for me, unless I refresh the page, it seems to create a new user every time I try to subscribe as a user. So in the firestore, it starts creating multiple users with the same email. Also, the Subscribe to Machine does not update right away when this happens. If i refresh thee page after pressing subscribe, it works perfectly finee

**Comment by merw957** [comment]
Don't merge this yet. I just realised my current fix constantly queries the user's machines from the database, which is using up a lot of our read quota on firestore. Working to fix this.

**Review by FrankWangma — APPROVED** [review]
LGTM!

**Pull request merged**
