### PR TITLE
Sets ups the sensor page

### PR DESCRIPTION
**Pull request by raghavgarg32**
Sets up the sensor page where other components need to be added

### CODE REVIEW

**Review by AlexanderTheGrape — CHANGES_REQUESTED** [review]
The deletion of the .prettierrc should not be pushed to master.
Otherwise LGTM, tested it and the page looks great.

**Review by KimberleyEvans-Parker — DISMISSED** [review]
Looks great, thanks Raghav!

Just change Alex's points and you're good :)

**Comment by raghavgarg32** [comment]
I added back .prettierrc

**Review by merw957 — APPROVED** [review]
Looks good 👍

**Pull request merged**
