### PR TITLE
Iot ingestor/real time data

### LINKED ISSUE #42: Make incoming input data files arrive real-time
As a prototype presenter, I want to see csv input data files arrive in a quick, but real-time manner so that I can show sensor data changing over time and receive notifications accordingly, as opposed to all at once.

**Acceptance Criteria**

 - Input csv files are "consumed" by the ingestor with a one file sent every 1 minute
 - A "fast mode" implemented to get to the threshold-breaking data quickly for testing/demo purposes.
 - Instructions are listed in PR and wiki
 - Any assumptions made are added to the assumptions doc on google drive and listed in PR.

**Is your feature request related to a problem? Please describe.**
We need to show a more realistic use case in which data comes in a timely, but not instant, way.

**Describe the solution you'd like**
A file feeder class separate from the ingestor class and file reader class, that copies in files for the ingestor/file reader class to read, staggered over a set time period.

The ingestor/file reader class should read these copied files and delete them, to prevent having to iterate through all prior read files to check for new ones.

**Describe alternatives you've considered**
No alternatives considered just yet.

**Additional context**

### PR DESCRIPTION
**Pull request by AlexanderTheGrape**
## GitHub Issue Solved:

closes #42 

## Current behaviour

Previously the ingestor read and process all input data files as fast as possible.

## Changed behaviour

The ingestor now has a simple delay that mimicks a more real-time speed, but at a speed that is useful for debugging. The speed can be changed via the delayInMilliseconds variable in ingestor.ts

## PR checklist

Remember to check the following

 - [x] Tag specific people to review your PR
 - [] Update the ReadMe with any new run instructions
 - [x] Closes the associated issue (if applicable)

## Notes

Madhu emailed during the demos today and said it's fine to simply slow the reading of input files, so this can be a permanent change.

### Demo

None needed, it's just the same console output but slower.

### Run instructions

With everything installed using `npm install` in the /api directory (and anything else the console says is missing), run `ts-node ingestor.ts` in api/functions/src/ingestor/

### CODE REVIEW

**Review by FrankWangma — CHANGES_REQUESTED** [review]
Looking good to me, just need to resolve the conflicts before I'll approve and merge

**Review by FrankWangma — CHANGES_REQUESTED** [review]
Not sure what happened, but I am getting this error now 
image

**Comment by margeobur** [comment]
> Not sure what happened, but I am getting this error now
> image

To test this, you'll now need to do the same setup as for the store-data PR. See #41

**Review by FrankWangma — APPROVED** [review]
Everything works, LGTM

**Pull request merged**
