### PR TITLE
Store data in Firestore from Ingestor

### LINKED ISSUE #16: Persisting Data
As a technician, I would like to store incoming data in a database, so that it can be used for historical data

**Acceptance Criteria**

 - Incoming data from the machines need to be stored in some kind of persistent database
 - The data needs to be processed and stored in a readable format, so raw data is not stored in the database

**Is your feature request related to a problem? Please describe.**
The PO mentioned that they want both historical and downloadable data to check for anomalies that have previously happened. They also want this to help see any trends in the defects. 

**Describe the solution you'd like**
A persistent database, which is stored in the cloud so that any user can access it at any time. This database needs to be accessible through the application, and the constant flow of data from the machine needs to be processed into a readable format (likely just large tables of information representing each machine).

**Describe alternatives you've considered**
N/A

**Additional context**
Split from #23

### PR DESCRIPTION
**Pull request by margeobur**
**WARNING** - you might find it easier to review this PR by checking out the branch and comparing it with master. There are a lot of changes so the diff might be a bit overwhelming

## Description 

This PR implements data persistence - the Ingestor now stores sensor data in Firestore as it reads it from the example dataset

Closes #16 

### Changes made

This PR refactors the existing ingestor code quite heavily to be more modular / less reliant on shared global state.

The Firebase admin SDK is used to instantiate a Firestore SDK module instance (see the top of `storeToFirebase.ts`). This is used to store RMS values in sampleChunks as they are parsed from the files

## How to test

You can run the ingestor using `ts-node` via the command line. You can run it from whatever working directory you like as long as you specify the path to `ingestor.ts` () however you will need to do `npm install` inside `api/functions` first.

You will also need to download a credentials file, located on the Google Drive (it's the JSON file). Create an environment variable `GOOGLE_APPLICATION_CREDENTIALS` with the path to that file.

BEFORE you run the script, please go into it and change the `machineID` and `sensorID` to the values for a different machine and sensor. You can create those by either going into firestore and manually creating documents, but probably the best way would be to run the graphQL API locally and invoke it with the playground (`npm run start` in the root of the project then go to `localhost:5001/industry4-uoa/us-central1/graph` in your browser).

Run these queries:
```
mutation {
  createMachine(name: "<whateverYouWant>") {
    success
    code
    message
    machine {
      id
    }
  }
}
```
use the id returned to do:
```
mutation {
  createSensor(input: {machineID: "<id>", name: "<whateverYouWant>"}) {
    success
    code
    message
    sensor {
      id
    }
  }
}
```

Then take both ids returned and set them as `machineID` and `sensorID` inside `ingestor.ts`.

Finally, you can run `ts-node <pathToIngestor>` from wherever you want. Head on over to the Firestore part of the Firebase console and watch your sensor get populated with data :)

### CODE REVIEW

**Comment by AlexanderTheGrape** [comment]
I couldn't find the `GOOGLE_APPLICATION_CREDENTIALS`.json file in the drive, if you could upload it that'd be awesome.
The instructions of "Create an environment variable" might make be obvious to some, but I don't know how to do this other than through my code editor or in console, which I'm assuming is not what you're meant to do (like as an extra parameter but as a cmd command?). A clarification would be real handy if this'll go into the readme

**Comment by margeobur** [comment]
The file is called industry4-uoa-firebase-adminsdk-ysxt9-a1123695c5.json - shoulda clarified sorry :) 

When I say environment variable, I do just mean a cmd prompt / bash env variable.
So, on windows if you're using command prompt you'd do 
`set GOOGLE_APPLICATION_CREDENTIALS="C:\path\to\file"`

In bash or zsh on any system it would be
`export GOOGLE_APPLICATION_CREDENTIALS="/path/to/file"`

**Comment by AlexanderTheGrape** [comment]
Thanks for the help so far. I've gotten to Playground, but it's currently returning null. Here's what I entered:
mutation {
  createMachine(name: "AlexTheMachine") {
    success
    code
    message
    machine {
      id
    }
  }
}

Here's what it returned:
{
  "data": {
    "createMachine": null
  }
}

Got any ideas why it returned null? Am I needing to fill in those other fields? On localhost 3000 it says "rc/components/LineGraph.tsx
Module not found: Can't resolve 'recharts' in 'C:\Users\Alex\Documents\Repos\industry-4\app\src\components'" and says it didn't compile, so it is likely due to something missing. I've run npm install in both app and api dirs, so am not sure what the issue is there.

**Comment by margeobur** [comment]
The localhost:3000 issue is a frontend problem - you can just do `npm install recharts` inside app\.

As for the query - that's kinda weird. I just copied that query into the playground, changed the name, ran it and it worked.

Screen Shot 2020-09-22 at 2 16 01 PM

**Comment by AlexanderTheGrape** [comment]
Interesting, localhost:5001/industry4-uoa/us-central1/graph doesn't even work for me any more so I can't send queries. I'll have to get your help on this tomorrow in a call I reckon

**Comment by AlexanderTheGrape** [comment]
We got it working with George's pc, and should otherwise work fine. We'll make another PR if more fixes are needed.

**Review by AlexanderTheGrape — APPROVED** [review]
LGTM

**Pull request merged**
